### ISSUE TITLE
Cannot launch from remote PC

### ISSUE THREAD

**Issue by MysticNynja** [cgarst/gamestream_launchpad#15]
I have tried adding the bat file to Geforce Experience but Playnite does not run.
I have tried running the bat file from the release download but Playnite does not run.
I have tried calling the gamestream_launchpad myself with the command from the .bat file and I get this error:
Traceback (most recent call last):
  File "gamestream_launchpad.py", line 140, in <module>
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[10500] Failed to execute script gamestream_launchpad

Also in the gamestream_desktop.ini the path should that be something like
C:/Games/
or
C:/Games/Playnite.FullscreenApp.exe
or
"C:/Games/"
or
"C:/Games/Playnite.FullscreenApp.exe"

**Comment by MysticNynja** [comment]
I have tried using the debug = 1 also but that does not keep the window running to see the error.  I had to run it from the command line to see the error above.

I will do some googling in the mean time

**Comment by MysticNynja** [comment]
I installed Python 3.8 and followed the developer setup here https://github.com/cgarst/gamestream_launchpad#developer-setup and I run the command to verify the install went well, but only get this 

![image](https://user-images.githubusercontent.com/11483359/106066415-6f2bde80-60c2-11eb-8e65-5684f4950897.png)

**Comment by MysticNynja** [comment]
Ok I got it to run.  I did it from a fresh cmd window.  With all of that I still get the same error.
