### ISSUE TITLE
Gamestream Launchpad failing to launch controller companion (poss winerror 740?)

### ISSUE THREAD

**Issue by BonesJones94** [cgarst/gamestream_launchpad#20]
Hey man really love launchpad for launching playnite to my shield TV! One thing ive found is that when I try and launch Controller Companion (Purchased through Steam) as a background .exe it  failes to open Playnite nor open Controler companion. An error Flahes up for a split second on the gamestream_launchpad.exe console and I managed to grab a print screen of it as follows -

Switching resolution to 1920x1080
Launching C:\Program Files (x86)\Steam\steamapps\common\Controller Companion\ControllerCompanion.exe
Traceback (most recent call last):
File "gamestream_launchpad.py", line 116, in <module>
File "subprocess.py", line 854, in__it__
File "subprocess.py", line 1307, in _execute_child
OsError: [WinError 740] The requested operation requires elevation
[18024] Failed to execute script gamestream_launchpad

I've previously used JoyToKey with no hiccups what so ever but recently started using controller comapnion as I like the seamlessness of it when switching between games and desktop.
Any help would be much appreciated, keep up the good work man, Thanks

**Comment by cgarst** [comment]
Much like #8 this process wants to be run as admin, but we don't yet have a mechanism to escalate privilege. Will consider this use case as part of that.
